### ISSUE TITLE
RFC: `scipy_namespace_for(xp)` helper?

### ISSUE THREAD

**Issue by izaid** [data-apis/array-api-compat#104]
Hello array-api-compat! Really great project and thanks for providing it. After several years of having internal libraries like this one, I have finally been able to switch to array-api-compat in many projects.

I have a suggestion for something that would be a valuable helper while SciPy fully transitions to supporting the array api. Right now, both CuPy and Jax have their own "scipy" submodules, in addition to SciPy itself of course. The issue is, as they are not standard, they are all in different places. CuPy's scipy is in `cupyx.scipy` and Jax's is in `jax.scipy`. NumPy doesn't have one, as the actual SciPy is that.

Would it be possible to add a function like `scipy_namespace_for(xp)` that simply returns the appropriate scipy submodule for a given array api (or raises an error for those that have none, like PyTorch)? This helps with writing array agnostic code. I'm happy to make a PR if this is fine with everyone.

The idea is that the following pattern could then be used:

```
xp = array_api_compat.array_namespace(x)
spx = array_api_compat.scipy_namespace_for(xp)

# do things
```

**Comment by rgommers** [comment]
> After several years of having internal libraries like this one, I have finally been able to switch to array-api-compat in many projects.

🎉 

> Would it be possible to add a function like `scipy_namespace_for(xp)` that simply returns the appropriate scipy submodule for a given array api

Given that coverage of SciPy APIs across CuPy, JAX and PyTorch is so sparse, and for NumPy and Dask non-existent, would this really be useful? It seems to me that you would not be able to rely on what's in `spx`, you'd have to check for each submodule and function you're using.

**Comment by izaid** [comment]
Thanks @rgommers! I do really think it would be very helpful.

CuPy's scipyx is actually really advanced, with coverage of the most important functions from `ndimage`, `linalg`, `special`, `sparse`, `stats`, and `optimize` among others. Heck, it even has its own GPU `KDTree` in `cupyx.scipy.spatial` now! Jax has less, but still a lot from `stats`, `special`, and `linalg` among others.

The fact that two of the most popular array libraries (CuPy and Jax) have their own subset of SciPy seems to indicate a real demand for it. Of course, in the long term, the dream is that these SciPy-like submodules disappear, to be replaced by the actual SciPy becoming array API compatible. But in the interim - which may last a few years - having a simple helper function like this would be very helpful to many of the scientific developers writing array agnostic code.

Here are some examples:

Example 1. I want to solve solve a large-scale matrix-free system with `gmres`. This is already supported now by `SciPy`, `CuPy`, and `Jax` as they all have `scipy.sparse.linalg.bicgstab` and other solvers. But one needs to get the particular namespace to do it.

Example 2: I want to compute the logpdf of a distribution, like the Cauchy distribution. Again, already in all the above packages as `scipy.stats.cauchy.*`.

Etc...

**Comment by izaid** [comment]
And a possible implemention could be:

```
def scipy_namespace_for(xp):
    if ((xp is np) or (xp is array_api_compat.numpy)):
        return scipy

    if (((xp is cp) or (xp is array_api_compat.cupy))):
        return cupyx.scipy

    if (xp is jax):
        return jax.scipy

   raise RuntimeError
   ```

**Comment by asmeurer** [comment]
I wonder if it would make more sense to have something like this in scipy itself.

**Comment by izaid** [comment]
@asmeurer I think the idea of having something like that in SciPy itself is an interesting one. @rgommers Any thoughts on that?

One argument for having it here would be due to the importance and overall specialness of SciPy in the numerical Python ecosystem. Obviously one couldn't start doing this for any package in a similar situation. But **are** there any other packages in similar situations?

**Comment by lucascolley** [comment]
Probably makes sense to put this in `scipy._lib._array_api.py` for now and upstream it _somewhere_ eventually, along with all the other things which we will build up that will be useful for the wider NumPy ecosystem. I'm inclined to agree with Aaron that that is out of scope for array-api-compat though - or at least, there is no need to commit to this being in-scope now, when it could live fine in a private SciPy module for now (I assume, unless you're wanting something that works with released versions).

**Comment by asmeurer** [comment]
I'm a little worried about scope creep in this package. I've written up what I think the scope for array-api-compat should be at https://data-apis.org/array-api-compat/#scope. I would argue that this request falls out of that scope, because it isn't something that is part of the standard. If you disagree, feel free to voice that concern, but I do think this would make more sense to live somewhere else, such as in scipy itself. Or at least, something about this should be added to the standard to justify wrapping it here.

**Comment by lucascolley** [comment]
@izaid happy to merge a PR for this to SciPy (if that is helpful for you at all), that should be uncontroversial as everything in that file is both private and experimental

**Comment by izaid** [comment]
Thanks both! And much appreciated @lucascolley, I will circle back on this soon.
