### ISSUE TITLE
`array_api_compat.numpy.asarray(torch.Tensor)` returns a `torch.Tensor`

### ISSUE THREAD

**Issue by izaid** [data-apis/array-api-compat#106]
This feels like a bug to me. My expectation is that `xp.asarray` converts to an array object in the `xp` namespace if that operation is supported.

```
>>> import torch
>>> import array_api_compat.numpy
>>> x = torch.arange(10)
>>> array_api_compat.numpy.asarray(x)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Comment by rgommers** [comment]
Agreed, that is a bug. This line looks wrong:
https://github.com/data-apis/array-api-compat/blob/d10bf57e73e88f692c59b420eb0c928abbb3db1c/array_api_compat/common/_aliases.py#L352

**Comment by ivirshup** [comment]
What is the expected behavior for `xp.asarray(some_other_array_type)`? Are there cases it should fail in?

**Comment by asmeurer** [comment]
If the input type is one of the types mentioned in the standard (in the type signature), it should convert that input type. Otherwise, generally for array-api-compat, any behavior outside of the standard should just pass through to the library function. So in this case, asarray() should indeed convert the input because normal `np.asarray(Tensor)` works (and also I think `Tensor` falls under the category of `SupportsBufferProtocol`).

**Comment by lithomas1** [comment]
Yeah, I messed up asarray. I have a WIP branch fixing that ,and some other dask stuff.

**Comment by asmeurer** [comment]
OK, I'll hold off on looking at this for now so I don't step on your toes. You may want to integrate the test from https://github.com/data-apis/array-api-compat/pull/109/files. It may also be necessary to update the copy logic generally similar to https://github.com/data-apis/array-api-strict/pull/15. I don't know if the "check if a copy was made" trick can work for cupy and dask, but if it can we should use it. If there end up being too many library-specific checks in the `asarray` code it may be more prudent to just split it into separate helpers for each library.

**Comment by lithomas1** [comment]
@izaid @ivirshup 

Are you able to test main again? I should have this bug fixed, but just wanted to make sure.

**Comment by izaid** [comment]
> @izaid @ivirshup
> 
> Are you able to test main again? I should have this bug fixed, but just wanted to make sure.

Is there a link somewhere with steps to follow? I only have `array_api_compat` installed from pip.

**Comment by lucascolley** [comment]
- clone `array_api_compat` main
- `cd array_api_compat`
- create a new env
- `pip install torch`
- then run your example above

should work?

**Comment by jowodo** [comment]
will this fix be released in version 1.5.1 and if so when approximately? 
thanks :)

**Comment by asmeurer** [comment]
I'm hoping to get a release out before the end of the week. I want to fix a few other issues that have cropped up too.

**Comment by asmeurer** [comment]
I just released 1.5.1 with this fix (and some others).

**Comment by asmeurer** [comment]
By the way, this still won't work for something like `np.asarray(cupy.array(...))` because CuPy explicitly errors when there would be an implicit device transfer to CPU.

**Comment by kburns** [comment]
> By the way, this still won't work for something like np.asarray(cupy.array(...)) because CuPy explicitly errors when there would be an implicit device transfer to CPU.

I'm running into exactly this, and it's very inconvenient. There are many points where I want to write general CPU code that converts device arrays to numpy first, and it seems `np.asarray(device_array)` would be perfect for this. But unfortunately, instead we have to make cases for different device backends to handle conversion to numpy, as I understand it. Or am I missing a conversion pathway that is input agnostic but endpoint specific? It seems like this would be a really useful part of the standard.

**Comment by lucascolley** [comment]
> am I missing a conversion pathway that is input agnostic but endpoint specific?

https://data-apis.org/array-api/latest/API_specification/generated/array_api.from_dlpack.html#from-dlpack
