### ISSUE TITLE
Dispatch objects with __array_function__ to the numpy compat layer

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-compat#15]
Right now we only dispatch np.ndarray and its subclasses to the numpy compat layer (in `get_namespace`), but we could also dispatch any object with the appropriate `__array_function__` dispatching methods as well. CC @seberg

**Comment by seberg** [comment]
Yeah, basically any object that has array function and array ufunc (even cupy) could be dispatched through the `numpy` namespace in practice.  For cupy, you probably should serve `cupy` directly, since that saves a tiny bit of overhead.

**Comment by rgommers** [comment]
This seems slightly questionable, if I understand the proposal correctly. For example, CuPy and Dask have `__array_function__`; there's now a `cupy` implementation, and in the future a `dask` one may be added. For "unknown"  (to this package) libraries, the array-consuming library may already have a strategy. E.g., for SciPy, the default/fallback is to coerce incoming objects that don't get detected as supporting the array API standard to `numpy.ndarray` instances. So the proposed change here would be an unexpected change (probably a regression).
