### ISSUE TITLE
`sign` complex case implementations

### ISSUE THREAD

**Issue by mdhaber** [data-apis/array-api-compat#183]
Since the 2022.12 standard, the required implementation of `sign` has been:

<img width="927" alt="image" src="https://github.com/user-attachments/assets/d2604867-948a-465a-83db-8cb68bf0ba0a">

but I think only the most recent versions of libraries follow this (if any). Older versions of all libraries and even the most recent versions of some (e.g. [CuPy](https://docs.cupy.dev/en/latest/reference/generated/cupy.sign.html), and even `array_api_strict`, which I can report separately if need be) use other conventions. It would be helpful if all libraries had aliases of `sign` that use the new definition.

**Comment by asmeurer** [comment]
sign for torch was already fixed at https://github.com/data-apis/array-api-compat/pull/137/files. I didn't realize cupy had the issue too. Do older versions of NumPy have this problem as well?

**Comment by mdhaber** [comment]
Yes. Basically everything needs to be patched unless it is recent enough. (I know the torch error would not be present with `array_api_compat` `main`, but this is what an environment on Colab looks like after `!pip install array_api_compat array_api_strict`.

```python3
import array_api_compat
print(array_api_compat.__version__)  # 1.8

from array_api_compat import numpy as xp
print(xp.__version__)  # 1.26.4
x = xp.asarray(1 + 2j)
print(xp.sign(x))  # (1+0j)

import cupy as cp
print(cp.__version__)  # 12.2.0
from array_api_compat import cupy as xp
x = xp.asarray(1 + 2j)
print(xp.sign(x))  # (1+0j)

import torch
print(torch.__version__)  # 2.4.1+cu121
from array_api_compat import torch as xp
x = xp.asarray(1 + 2j)
# print(xp.sign(x))  # RuntimeError: Unlike NumPy, torch.sign is not intended to support complex numbers. Please use torch.sgn instead.

import dask
print(dask.__version__)  # 2024.8.0
from array_api_compat.dask import array as xp
x = xp.asarray(1 + 2j)
print(xp.sign(x))  # dask.array<sign, shape=(), dtype=complex128, chunksize=(), chunktype=numpy.ndarray>

import array_api_strict as xp
print(xp.__version__)  # 2.0.1
x = xp.asarray(1 + 2j)
print(xp.sign(x))  # (1+0j)
```

**Comment by asmeurer** [comment]
Interesting. The test suite should be checking this as far as I can tell, but it hasn't come up, even though we do explicitly test against older versions of NumPy. That will require some investigation.

**Comment by asmeurer** [comment]
So I dug into this and it looks like the test suite has been ignoring any exceptions raised in the reference implementations in the elementwise function tests. This appears to affect quite a few functions, although it isn't clear yet if there are any actual unwrapped incompatibilities due to this other than this `sign` one that you've pointed out.
