### ISSUE TITLE
rename or alias `get_namespace` to `array_namespace`

### ISSUE THREAD

**Issue by ntessore** [data-apis/array-api-compat#19]
Having a function `array_namespace` seems more intuitive than `get_namespace`, mainly due to symmetry with e.g. `repr()`, `str()`, `iter()`, `next()`, since `array_namespace(x)` returns `x.__array_namespace__()` if it exists, and does something sensible if it does not.

**Comment by ntessore** [comment]
That's expected, of course, but I thought I should bring this up at least while the NEP is still a draft.

**Comment by asmeurer** [comment]
I agree it does seem like a better name to match `__array_namespace__`. We would probably want to keep `get_namespace` too if we change it just because we did already do a release with it.

**Comment by asmeurer** [comment]
I'm actually in favor of this, but I've made it as a separate PR in case there are any objections https://github.com/data-apis/array-api-compat/pull/29. I kept `get_namespace` as an (undocumented) backwards compatible wrapper.
