### ISSUE TITLE
using current main (d7b4111954405abb84f1819aa43443dcf34cf940)  in scipy breaks down 

### ISSUE THREAD

**Issue by ev-br** [data-apis/array-api-compat#193]
scipy uses `array_api_compat` as a submodule. 
Updating the submodule to the current main with

```diff
$ git diff HEAD^
diff --git a/scipy/_lib/array_api_compat b/scipy/_lib/array_api_compat
index f905d8c299..d7b4111954 160000
--- a/scipy/_lib/array_api_compat
+++ b/scipy/_lib/array_api_compat
@@ -1 +1 @@
-Subproject commit f905d8c299e626aa2902f21b75df3a42507a8436
+Subproject commit d7b4111954405abb84f1819aa43443dcf34cf940
```

breaks down running scipy tests:

```
$ python dev.py test -t scipy/signal/tests/test_filter_design.py::TestOrderFilter -v 
💻  ninja -C /home/ev-br/repos/scipy/build -j32
ninja: Entering directory `/home/ev-br/repos/scipy/build'
[1/1] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed --tags runtime,python-runtime,tests,devel
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /home/ev-br/repos/scipy/build-install/lib/python3.11/site-packages
Running tests for scipy version:1.15.0.dev0+git20241101.e21d600, installed at:/home/ev-br/repos/scipy/build-install/lib/python3.11/site-packages/scipy
ImportError while loading conftest '/home/ev-br/repos/scipy/build-install/lib/python3.11/site-packages/scipy/conftest.py'.
scipy/conftest.py:15: in <module>
    from scipy._lib._array_api import SCIPY_ARRAY_API, SCIPY_DEVICE
scipy/_lib/_array_api.py:21: in <module>
    from scipy._lib.array_api_compat import (
scipy/_lib/array_api_compat/numpy/__init__.py:7: in <module>
    from ._aliases import * # noqa: F403
scipy/_lib/array_api_compat/numpy/_aliases.py:7: in <module>
    from ._info import __array_namespace_info__
E   ModuleNotFoundError: No module named 'scipy._lib.array_api_compat.numpy._info'
```

(Here I only request a specific subset of scipy tests, but that's irrelevant; it just simplifies bisections)

Bisecting from a known good version (the one in the diff above) blames

```
$ git bisect good
11cb6ef8446a0703fe22e40f0a168d70f539aefa is the first bad commit
commit 11cb6ef8446a0703fe22e40f0a168d70f539aefa
Author: Aaron Meurer <asmeurer@gmail.com>
Date:   Mon Aug 19 15:34:01 2024 -0600

    Add NumPy inspection namespace

 array_api_compat/numpy/_aliases.py |  11 +-
 array_api_compat/numpy/_info.py    | 346 +++++++++++++++++++++++++++++++++++++
 2 files changed, 353 insertions(+), 4 deletions(-)
 create mode 100644 array_api_compat/numpy/_info.py
```

Weirdly enough, if I just clone `array_api_compat` standalone, all is well:

```
(scipy-dev) ev-br@qgpu3:~/repos/array-api-compat$ ipython
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from array_api_compat.numpy import _info

In [2]: _info.__array_namespace_info__
Out[2]: numpy.__array_namespace_info__

```

**Comment by asmeurer** [comment]
This probably isn't related to your issue, but I would suggest pinning to the latest release tag, not `main`.

**Comment by asmeurer** [comment]
Does the `scipy/_lib/array_api_compat/numpy/_info.py` file exist?

**Comment by ev-br** [comment]
It's `array_api_compat/array_api_compat/numpy/...`, and yes:

```
$ ll scipy/_lib/array_api_compat/array_api_compat/numpy/_info.py
-rw-rw-r-- 1 ev-br ev-br 10384 Nov  1 19:10 scipy/_lib/array_api_compat/array_api_compat/numpy/_info.py
```

**Comment by asmeurer** [comment]
The file I mentioned (with only one `array_api_compat`) is the one that it's trying to import in your traceback. There could be an issue with the layering in your submodule. I don't know how you are doing that.

**Comment by ev-br** [comment]
That file does not exist indeed. And it should not --- scipy has `array_api_compat` as a git submodule, cf https://github.com/scipy/scipy/tree/main/scipy/_lib
That's fairly standard, I guess?

**Comment by asmeurer** [comment]
How does it work, though? array_api_compat is the repo, which contains the module as a directory. The repo does not have an `__init__.py` file. Ideally you'd want to vendor just the `array_api_compat` module, not the whole repo.

**Comment by ev-br** [comment]
OK, it _is_ a scipy issue in the end. The missing bit was that submodule sources get copied during the build, from the submodule path (two `array_api_compat`s) into the built tree with a single `array_api_compat`:
 notice the `subdir` argument at https://github.com/scipy/scipy/blob/main/scipy/_lib/meson.build#L141

It's a bit annoying to have to follow the implementation details like a new `_info.py` source file. Mostly because it's rare enough to forget that the private layout details need to be specified somehwere outside of the submodule tree.

Thanks for the discussion, and sorry for the noise!

**Comment by asmeurer** [comment]
That seems like a rather confusing way that SciPy does things. But maybe there are good reasons for it.
