### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-compat#2]
We need to think about how we want to version this. Do we want to use 1.0 style versions or date versioning? Are there any considerations that we should think about for the fact that many people will want to vendor this?

**Comment by asmeurer** [comment]
If no one has any preferences any way here, I'm going to just version this like 1.0, 1.1, and so on (because that's my personal preference for how to version things).

**Comment by honno** [comment]
I think SemVer *could* get awkward if say something diverges just for one namespace version `x.__array_namespace__(version=...)`, but no need to be pre-emptive about it (i.e. can figure out then if major version changes are enough of a headache to say adopt CalVer).

But yeah, my 2 cents is 1.0 style versioning makes sense.
