### ISSUE TITLE
Release 1.10.0

### ISSUE THREAD

**Issue by crusaderky** [data-apis/array-api-compat#217]
I would need [array-api-compat#205](https://github.com/data-apis/array-api-compat/pull/205) to be released ASAP,
which in turn would allow @lucascolley to merge [array-api-extra#53](https://github.com/data-apis/array-api-extra/pull/53) and cut a new release of array-api-extra,
which in turn would allow [scipy#22070](https://github.com/scipy/scipy/pull/22070) to be merged,
which in turn would unblock all work on scipy to implement `at(...)` for JAX assignment.

For this purpose, can we have a new release of array-api-compat?

I think it should be numbered 1.10.0 as it's part of a major feature (JAX's `at` assignment paradigm) so I don't want people to think they can downgrade to an earlier patch version without breaking things.

CC @rgommers @ev-br

**Comment by ev-br** [comment]
@asmeurer any objections?

**Comment by ev-br** [comment]
https://pypi.org/project/array-api-compat/1.10.0/ is up on PyPI @crusaderky
