### ISSUE TITLE
torch.zeros can not pass shape as keyword argument

### ISSUE THREAD

**Issue by thomasjpfan** [data-apis/array-api-compat#22]
```python
import array_api_compat
import torch

x = torch.asarray([1.0, 2.0, 3.0])
xp = array_api_compat.get_namespace(x)
xp.zeros(shape=(8, 4))
# TypeError: zeros() missing 1 required positional arguments: "size"
```

**Comment by rgommers** [comment]
Indeed, `shape` isn't positional-only so that will need some mapping from `shape` to `size`.

**Comment by asmeurer** [comment]
This is something I would have expected the test suite to catch. @honno 

Either way, the fix here is easy. We just need to add a wrapper for `zeros` using the spec signature.
