### ISSUE TITLE
raise TypeError in get_namespace

### ISSUE THREAD

**Issue by ntessore** [data-apis/array-api-compat#26]
This is a very minor point, but it has just tripped me up. The `get_namespace` helper could raise `TypeError` instead of `ValueError` when the arguments are of incompatible or inconsistent types, particularly since the values of the inputs are never inspected.

For reference:

> *exception* **TypeError**
>
> Raised when an operation or function is applied to an object of inappropriate type. The associated value is a string giving details about the type mismatch.
> 
> This exception may be raised by user code to indicate that an attempted operation on an object is not supported, and is not meant to be. [...]
>
> Passing arguments of the wrong type (e.g. passing a list when an int is expected) should result in a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError), but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError).
>
> *exception* **ValueError**
>
> Raised when an operation or function receives an argument that has the right type but an inappropriate value [...].

**Comment by asmeurer** [comment]
Agreed. Fixed in #25
