### ISSUE TITLE
Should torch.reshape support integer shape?

### ISSUE THREAD

**Issue by thomasjpfan** [data-apis/array-api-compat#28]
`torch.reshape` requires an tuple as the shape:

```python
import torch
import array_api_compat 

x = torch.asarray([1.0, 2.0])
xp = array_api_compat.get_namespace(x)

# works
xp.reshape(x, (-1,))

xp.reshape(x, -1)
# TypeError: reshape(): argument 'shape' (position 2) must be tuple of ints, not int
```

Note that integer `shape` works with `numpy.array_api`:

```python
import numpy.array_api as np
import array_api_compat 

x = np.asarray([1.0, 2.0])
xp = array_api_compat.get_namespace(x)

xp.reshape(x, -1)
```

**Comment by asmeurer** [comment]
This looks like a bug in numpy.array_api. `reshape` in the spec only accepts a tuple (in all versions of the spec) https://data-apis.org/array-api/draft/API_specification/generated/array_api.reshape.html#array_api.reshape

**Comment by asmeurer** [comment]
Looks like `broadcast_to` and the `axis` argument of `permute_dims` also have this issue. We might consider changing this in the spec. Most other places that accept shape or axis accept both an int or tuple of ints.

**Comment by asmeurer** [comment]
Let's see what the decision here is. https://github.com/data-apis/array-api/issues/608. We should probably update numpy.array_api either way.

**Comment by asmeurer** [comment]
Of course, we can still work around this in the wrappers here. But it wouldn't be portable to other array API compliant libraries (not that any necessarily exist). But this should be too hard to work around in upstream code either.

**Comment by rgommers** [comment]
I think the `numpy`.array_api` support for ints is a bug indeed, and requiring a tuple is good practice here. It's easy to fix this up in scikit-learn, so I suggest doing it there rather than in this repo.
