### ISSUE TITLE
Should `numpy_array_api_compat` installable?

### ISSUE THREAD

**Issue by thomasjpfan** [data-apis/array-api-compat#4]
For testing, I added a `pyproject.toml` to this repo so I can install it and import it. I can see libraries vendoring this library, but I think it would be nice to have the option to install it as well.

Should `numpy_array_api_compat` install-able?

**Comment by asmeurer** [comment]
Yes, I plan to make it installable. I was hoping for feedback first before I did a release, but I can see that making it at least basically installable will help with the release as well. I also think we might want to rename it before doing so. For one thing, we will likely support more than just NumPy (#3), and also the name is a little too long IMO. Maybe just `array_api_compat`?

**Comment by asmeurer** [comment]
There's also the question of how to do the versioning https://github.com/data-apis/numpy-array-api-compat/issues/2.

**Comment by asmeurer** [comment]
It's released on PyPI now. I still need to add it to conda-forge.
