### ISSUE TITLE
Support for xp.linalg.lu (not yet part of the Array API spec)

### ISSUE THREAD

**Issue by ogrisel** [data-apis/array-api-compat#45]
Context adding LU factorization to the Array API spec:

- https://github.com/data-apis/array-api/issues/627

Since `numpy.linalg.lu` does not exist yet (but `scipy.linalg.lu` does), @rgommers suggested working out an API candidate as part of `array-api-compat` first by reviewing the API choices and options implemented in various libraries targeting Array API support.

A short term implementation for numpy could probably delegate the work to `scipy.linalg.lu` in a first iteration.

Based on this work, `numpy.linalg` could subsequently be extended to directly implement the correct API to be submitted for a future revision of the spec.

Motivation: this is needed to add Array API support to the randomized linear algebra solver for the Principal Component Analysis estimator in scikit-learn:

- https://github.com/scikit-learn/scikit-learn/pull/26315

Non exhaustive list of available implementations:

- [scipy.linalg.lu](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html)
- [cupyx.scipy.linalg.lu](https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.linalg.lu.html)
- [torch.linalg.lu](https://pytorch.org/docs/stable/generated/torch.linalg.lu.html)
- [jax.scipy.linalg.lu](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.linalg.lu.html)
- [dask.array.linalg.lu](https://docs.dask.org/en/stable/generated/dask.array.linalg.lu.html)
- ...

Related methods in scipy:

- [scipy.linalg.lu_factor](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html)
- [scipy.linalg.lu_solve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_solve.html)

**Comment by rgommers** [comment]
Thanks @ogrisel! It looks like you only have a single usage in scikit-learn ([here](https://github.com/scikit-learn/scikit-learn/blob/55af30d981ea2f72346ff93602f0b3b740cfe8d6/sklearn/utils/extmath.py#L278-L279)), with `lu(x, permute_l=True)`, so if that is covered you should be good for now, right?

I think for the API design decisions, it's best to put them on https://github.com/data-apis/array-api/issues/627. And then let's implement it here. I'll try to post some thoughts there within the next few hours.

**Comment by ogrisel** [comment]
> It looks like you only have a single usage in scikit-learn (here), with lu(x, permute_l=True), so if that is covered you should be good for now, right?

Yes, this is also what I found out via `git grep`.

**Comment by rgommers** [comment]
That sounds like the right thing to do to me, we don't want this package to have a direct dependency on `scipy`.

**Comment by asmeurer** [comment]
Based on the [scope of array-api-compat](https://data-apis.org/array-api-compat/#scope), `lu` should be added first to a draft version of the standard. Then we can add it here. It's better to discuss design specifics of it in the array-api repo. For actual implementations, it would be better to discuss that with specific libraries. 

Regarding the scipy question, if `lu` were added, I wouldn't see an issue with making only that function (in the numpy wrapper) depend on scipy.

**Comment by asmeurer** [comment]
Closing this as it's out of scope here as long as `lu` isn't in the standard. The better place for it to go as long as it isn't is the array-api-extra package https://github.com/data-apis/array-api-extra
