### ISSUE TITLE
Interest in publishing workflows?

### ISSUE THREAD

**Issue by matthewfeickert** [data-apis/array-api-compat#50]
At the moment it seems like there is no CI/CD publishing infrastructure for `array-api-compat`. Is there interest in setting up a GitHub Actions based workflow that uses [PyPI trusted publishers](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) to deploy to TestPyPI and PyPI?

The [workflow that we use for `pyhf`](https://github.com/scikit-hep/pyhf/blob/ff9cb94025e5485b23ea81a06ce8916055297c7f/.github/workflows/publish-package.yml) does this and publishes on GitHub Release or workflow dispatch (but can be easily configured to work with tags or anything).

**Comment by asmeurer** [comment]
Yes, this would be useful. The packaging here is currently just a minimal thing that I set up. Feel free to modify the packaging to use something better. We just need to make sure that whatever we do we still support vendoring, and that we don't have any hard dependencies on any array library.
