### ISSUE TITLE
Compatibility problem with pytorch trace

### ISSUE THREAD

**Issue by jplumail** [data-apis/array-api-compat#52]
`torch.linalg.trace` should work on [stacks of matrices](https://data-apis.org/array-api/latest/extensions/generated/array_api.linalg.trace.html?highlight=(...,%20M,%20N)).

But this
```python
import array_api_compat.torch as torch

a = torch.reshape(torch.arange(10*5*5), (10,5,5))
torch.linalg.trace(a)
```
throws `RuntimeError: trace: expected a matrix, but got tensor with dim 3`.

The pytorch's `trace` function doesn't handle stacks: [see the docs](https://pytorch.org/docs/stable/generated/torch.trace.html).

**Comment by asmeurer** [comment]
Thanks for the report. What's a good way to work around this @lezcano

**Comment by lezcano** [comment]
`x.diagonal(0, -2, -1).sum(-1)`
