### ISSUE TITLE
AttributeError: module 'array_api_compat.torch' has no attribute 'newaxis'

### ISSUE THREAD

**Issue by ogrisel** [data-apis/array-api-compat#64]
According to:

- https://data-apis.org/array-api/latest/API_specification/generated/array_api.constants.newaxis.html

the namespace modules should expose an alias to `None` named `newaxis` to make indexing code more explicit.

However it seems to be missing in `array-api-compat`, at least for PyTorch:

```python
>>> import array_api_compat.torch as xp
>>> xp.newaxis is None
Traceback (most recent call last):
  Cell In[6], line 1
    xp.newaxis
AttributeError: module 'array_api_compat.torch' has no attribute 'newaxis'
```

Note, the same snippet works with numpy:

```python
>>> import array_api_compat.numpy as xp
>>> xp.newaxis is None
True
```

**Comment by asmeurer** [comment]
I guess newaxis isn't in the main torch namespace. I would have expected this to be caught by the test suite, but I guess not.
