### ISSUE TITLE
JAX support

### ISSUE THREAD

**Issue by imh** [data-apis/array-api-compat#83]
> If you want support for other array libraries, or if you encounter any issues, please [open an issue](https://github.com/data-apis/array-api-compat/issues).

Okay, well here it is. I don't know if I'd have time to add it myself in the near future, but it would be great to have.

**Comment by asmeurer** [comment]
@jakevdp has been working on adding array API support to JAX. I think his plan was to have full support in a JAX submodule so that array-api-compat library support would be unnecessary, but maybe he can clarify if that's still the plan and what the latest status of that is.

**Comment by jakevdp** [comment]
Hi - thanks for the ping! We are tracking JAX Array API support here: https://github.com/google/jax/issues/18353

You can experimentally enable it by importing `jax.experimental.array_api`:
```python
import jax.numpy as jnp

# This is a side-effecting import that among other
# things adds __array_namespace__ to JAX arrays.
import jax.experimental.array_api

xp = jnp.array(0).__array_namespace__()
print(xp.arange(10))
# [0 1 2 3 4 5 6 7 8 9]
```
There are still some fundamental questions, though: for example, JAX arrays are immutable so they cannot support pieces of the API standard that require mutability. But we're gradually ironing out those details and are hoping to have the main `jax.numpy` namespace be array API-compliant in a future release.

**Comment by asmeurer** [comment]
So with `__array_namespace__` defined, array-api-compat will automatically work

```py
>>> import jax.experimental.array_api as xp
>>> import array_api_compat
>>> array_api_compat.get_namespace(xp.arange(10)) is xp
True
```

I think the main thing to do here is to add jax support to the [`device()`](https://github.com/data-apis/array-api-compat/blob/main/array_api_compat/common/_helpers.py#L128) helper function. 

I don't think it's necessary to add an `array_api_compat.jax` wrapper namespace to wrap JAX functions that aren't compliant because that is effectively already the `jax.experimental.array_api` namespace. 

> # This is a side-effecting import that among other
> # things adds __array_namespace__ to JAX arrays.

What are the other things it does? I would suggest not using a side-effecting import, but rather just add `__array_namespace__` to JAX arrays, and if there is any patching or something that needs to happen, do it when `__array_namespace__()` is called. 

Otherwise, whether jax.numpy arrays will work with a library like scipy will depend on whether the user (or someone else) has already imported `jax.experimental.array_api` or not.

**Comment by jakevdp** [comment]
The only other patching currently is adding the `to_device` method, which is a bit of a hack currently until we can finish the `device` method deprecation.

> Otherwise, whether jax.numpy arrays will work with a library like scipy will depend on whether the user (or someone else) has already imported `jax.experimental.array_api` or not.

This is the intent right now: the array API is not ready to be a supported feature of JAX arrays. But in the future when we've gotten to the point that we can advertise non-experimental support, the import will no longer be necessary.

**Comment by asmeurer** [comment]
array-api-compat also has a `to_device` helper (JAX isn't the only library without these methods). In practice people using the array API today are doing it through array-api-compat, so if we just add JAX support for those helper methods here, it will be good enough for most array API users. 

> This is the intent right now: JAX is not yet ready to non-experimentally support the array API. But in the future when we've gotten to the point that we can advertise non-experimental support, the import will no longer be necessary.

So should we go ahead and fix the array-api-compat `device` and `to_device` helpers now to support JAX, or wait for the support to be fleshed out more?

**Comment by jakevdp** [comment]
Interesting - thanks. Realistically it will be 1-2 months more before we can do a JAX release with compatible `device` and `to_device` support, so we could support it via `array-api-compat` until then. What do you think? I can put together a PR if you'd like.

**Comment by lucascolley** [comment]
IMO it would make sense to just wait the 1-2 months to avoid extra work here. Support from consumer libraries is still quite sparse and probably won't move forward a huge amount in the next 2 months (and being able to test with JAX a month or so earlier probably won't accelerate things).

**Comment by asmeurer** [comment]
Either way. It really isn't hard to add it here.

**Comment by ntessore** [comment]
As a consumer library maintainer, I am accessing the Array API through `array_api_compat.array_namespace()` for the foreseeable future anyway. As far as I understand, once JAX supports `__array_namespace__` natively, all it takes is to remove the special casing here, right? Having JAX access early, and being able to potentially feed issues back, would be nice.

**Comment by asmeurer** [comment]
OK, I've added basic JAX support to the helper functions at https://github.com/data-apis/array-api-compat/pull/84.

**Comment by imh** [comment]
Thank you!!
