### ISSUE TITLE
Pytorch support

### ISSUE THREAD

**Issue by asmeurer** [data-apis/array-api-compat#9]
I am working on adding support for pytorch. A good basis for this work is @pmeier's wrapper code at  https://github.com/data-apis/array-api-tests/compare/master...pmeier:array-api-tests:pytorch, and also @AnirudhDagar scipy pytorch demo https://github.com/scipy/scipy/compare/main...AnirudhDagar:scipy:array-api-demo.

**Comment by pmeier** [comment]
Keep in mind I haven't updated my fork in ~6 months.

**Comment by rgommers** [comment]
This was fixed by gh-14. PyTorch support is well-exercised by now.
